CREATE TABLE `game_eu` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `unique_id` varchar(100) COLLATE utf8mb4_unicode_ci,
  `fs_id` varchar(50),
  `nsuid` varchar(20),
  `name` varchar(255),
  `game_desc` text,
  `release_date` date,
  `url` varchar(255),
  `img` varchar(255),
  `boxart` varchar(255),
  `publisher` varchar(255),
  `product_code` varchar(255),
  `genres` varchar(255),
  `price` decimal(10,2) COMMENT '建议售价(欧元)',
  `lowest_price` decimal(10,2) COMMENT '史低价格(欧元)',
  `has_digital_version` tinyint COMMENT '有无数字版',
  `has_physical_version` tinyint COMMENT '有无实体卡',
  `eshop_removed` tinyint COMMENT '是否在eshop中被移除',
  `num_of_players` varchar(100),
  `pretty_agerating` varchar(100) COMMENT '年龄分级',
  `age_rating_type` varchar(20) COMMENT '分级类别',
  `age_rating_value` varchar(20) COMMENT '分级取值',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk` (`unique_id`),
  KEY `nsu_idx` (`nsuid`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
