CREATE TABLE `review` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cn_name` varchar(255) COLLATE utf8mb4_unicode_ci,
  `en_name` varchar(255),
  `jp_name` varchar(255) COLLATE utf8mb4_unicode_ci,
  `purchased` varchar(10) COMMENT '是否购买' COLLATE utf8mb4_unicode_ci,
  `played` varchar(10) COMMENT '是否聚会玩过' COLLATE utf8mb4_unicode_ci,
  `developers` varchar(255) COLLATE utf8mb4_unicode_ci,
  `publishers` varchar(255) COLLATE utf8mb4_unicode_ci,
  `developer_type` varchar(255) COLLATE utf8mb4_unicode_ci,
  `switch_only` varchar(10) COMMENT '是否Switch独占' COLLATE utf8mb4_unicode_ci,
  `party_type` varchar(10) COMMENT '协作/竞争' COLLATE utf8mb4_unicode_ci,
  `genre` varchar(50),
  `topic` varchar(50),
  `metacritic_rating` varchar(50),
  `price` varchar(10),
  `num_of_players` varchar(50) COMMENT '人数范围',
  `screen_use` varchar(50) COMMENT '分屏/同屏',
  `has_cn` varchar(50) COMMENT '中文',
  `somatic_game` varchar(50) COMMENT '体感',
  `game_desc` varchar(500) COMMENT '简介',
  `game_review` varchar(500) COMMENT '简评',
  `remark` varchar(255) COMMENT '备注',
  `rating` varchar(10) COMMENT '评分-综合',
  `rating_difficulty` varchar(10) COMMENT '评分-易上手度',
  `rating_joy` varchar(10) COMMENT '评分-欢乐度',
  `rating_smooth` varchar(10) COMMENT '评分-流畅度',
  `rating_playable` varchar(10) COMMENT '评分-耐玩度',
  `recommend_num_of_player` varchar(10) COMMENT '推荐人数',
  `stage` varchar(10) COMMENT '阶段分类',
  `duration_per_game` varchar(100) COMMENT '单局时长',
  `recommend_total_duration` varchar(10) COMMENT '建议总时长',
  `recommend_level` varchar(10) COMMENT '建议游戏水平',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk` (`cn_name`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;